import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import styles from '../styles/Main.module.scss';

const Home: NextPage = () => {
  return (
    <>
      <Header></Header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bodyWrapper}>
        <div className={styles.mainImage}>
          <div>
            <span>프로젝트 업로드</span>
          </div>
        </div>
        <div className={styles.leftWrapper}>
          <ul>
            <li>
              <span>🌏 전체</span>
            </li>
            <li>
              <span>😁 예능</span>
            </li>
            <li>
              <span>🚲 다큐멘터리</span>
            </li>
            <li>
              <span>🎞 영화</span>
            </li>
            <li>
              <span>🎥 드라마</span>
            </li>
            <li>
              <span>✏ 애니메이션</span>
            </li>
            <li>
              <span>📣 광고</span>
            </li>
            <li>
              <span>🎵 음악</span>
            </li>
            <li>
              <span>👟 스포츠</span>
            </li>
            <li>
              <span>🎮 게임</span>
            </li>
          </ul>
        </div>
        <div className={styles.rightWrapper}>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
          <h1>Hello</h1>
        </div>
      </div>
    </>
  );
};

export default Home;
