import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import MainLayout from '../components/MainLayout';
import { SELECTED_MENU_CHANGE } from '../reducers/main';
import { useDispatch, useSelector } from 'react-redux';
import { projectItem, RootState } from '../reducers';
import ProjectItem from '../components/ProjectItem';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { projectList } = useSelector((state: RootState) => state.project);

  dispatch({
    type: SELECTED_MENU_CHANGE,
    data: 'all',
  });
  return (
    <>
      <Header></Header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout selectedMenu={'all'}>
        {projectList.map((v: projectItem) => {
          return (
            <>
              <ProjectItem
                projectItem={v}
                case={false}
                rankingNum={null}
              ></ProjectItem>
            </>
          );
        })}
      </MainLayout>
    </>
  );
};

export default Home;
